CREATE SCHEMA IF NOT EXISTS DB2CBO AUTHORIZATION sa;

CREATE TABLE IF NOT EXISTS DB2CBO.CRS_BCRO (
	CD_CRS INTEGER NOT NULL,
	DT_CADM DATE DEFAULT '0001-01-01' NOT NULL,
	CD_TIP_CRS INTEGER NOT NULL,
	CD_EST_ATVD SMALLINT NOT NULL,
	VL_LIM_ECXE_CRS DECIMAL(17,2) NOT NULL,
	VL_ECXE_UTZD DECIMAL(17,2),
	IN_BLQ_AUTC CHAR(1),
	CD_FMA_RCBT_RMNC SMALLINT NOT NULL,
	CD_PERC_RCBT_RMNC SMALLINT NOT NULL,
	DD_RCBT_RMNC SMALLINT NOT NULL,
	DT_ULT_RCBT_RMNC DATE,
	IN_RCBT_RMNC_DT CHAR(1),
	CD_RMS_ARQ_RTN SMALLINT,
	CD_FRNC_ETR_REDE INTEGER,
	CD_CHV_USU CHAR(8),
	DT_ALT DATE NOT NULL,
	HR_ALT TIME NOT NULL,
	CD_CVN_CRS INTEGER NOT NULL,
	CD_INST SMALLINT DEFAULT 1 NOT NULL,
	CD_GST_REDE_CRS INTEGER,
	VL_PGTO_UTZD DECIMAL(17,2) NOT NULL,
	VL_RCBT_UTZD DECIMAL(17,2) NOT NULL,
	IN_AUTZ_AUTC CHAR(1) DEFAULT 'N' NOT NULL,
	QT_DD_ALNM SMALLINT DEFAULT 2 NOT NULL,
	NM_CRS CHAR(30),
	IN_ALNM_AUTC CHAR(1),
	IN_ANOT_CRD CHAR(1) DEFAULT 'N' NOT NULL,
	IN_ANOT_CADL CHAR(1) DEFAULT 'S' NOT NULL,
	TX_NOTA_TCN_CRS CHAR(100),
	QT_DD_ISN_ENCG SMALLINT DEFAULT 0 NOT NULL,
	PRIMARY KEY (CD_INST, CD_CRS)
);

CREATE TABLE IF NOT EXISTS DB2CBO.HST_CRS_BCRO (
	CD_CRS INTEGER NOT NULL,
	DT_ALT DATE NOT NULL,
	HR_ALT TIME NOT NULL,
	DT_CADM DATE NOT NULL,
	CD_TIP_CRS INTEGER NOT NULL,
	CD_EST_ATVD SMALLINT NOT NULL,
	VL_LIM_ECXE_CRS DECIMAL(17,2) NOT NULL,
	VL_ECXE_UTZD DECIMAL(17,2),
	IN_BLQ_AUTC CHAR(1),
	CD_FMA_RCBT_RMNC SMALLINT NOT NULL,
	CD_PERC_RCBT_RMNC SMALLINT NOT NULL,
	DD_RCBT_RMNC SMALLINT NOT NULL,
	DT_ULT_RCBT_RMNC DATE,
	IN_RCBT_RMNC_DT CHAR(1),
	CD_RMS_ARQ_RTN SMALLINT,
	CD_FRNC_ETR_REDE INTEGER,
	CD_CHV_USU CHAR(8),
	CD_CVN_CRS INTEGER DEFAULT 0 NOT NULL,
	CD_INST SMALLINT DEFAULT 1 NOT NULL,
	CD_GST_REDE_CRS INTEGER DEFAULT 0 NOT NULL,
	IN_AUTZ_AUTC CHAR(1) DEFAULT 'N' NOT NULL,
	QT_DD_ALNM SMALLINT DEFAULT 0 NOT NULL,
	CD_JST_ALT SMALLINT,
	IN_ALNM_AUTC CHAR(1),
	IN_ANOT_CRD CHAR(1) DEFAULT 'N' NOT NULL,
	IN_ANOT_CADL CHAR(1) DEFAULT 'S' NOT NULL,
	TX_NOTA_TCN_CRS CHAR(100),
	QT_DD_ISN_ENCG SMALLINT DEFAULT 0 NOT NULL,
	PRIMARY KEY (CD_INST, CD_CRS, DT_ALT,HR_ALT)
);

CREATE TABLE IF NOT EXISTS DB2CBO.IDFC_ACSS_CRS (
	CD_INST SMALLINT DEFAULT 1 NOT NULL,
	CD_IDFC_CRS CHAR(8) NOT NULL,
	CD_EST_ATVD SMALLINT NOT NULL,
	CD_CRS INTEGER NOT NULL,
	NR_ULT_SEQL_IDFC INTEGER,
	CD_CHV_USU CHAR(8) NOT NULL,
	DT_ALT DATE NOT NULL,
	HR_ALT TIME NOT NULL,
	CD_OPRD_CRS INTEGER DEFAULT 0 NOT NULL,
	CD_ACSS_PRVR_OPRD INTEGER DEFAULT 0 NOT NULL,
	CD_LOJA_CRS INTEGER DEFAULT 0 NOT NULL,
	DT_INC_BLQ_NEGL DATE,
	DT_FIM_BLQ_NEGL DATE,
	CD_EST_ATVD_BLQ SMALLINT,
	CD_TIP_BLQ_NEGL SMALLINT,
	TX_JST_BLQ_NEGL VARCHAR(500),
	CONSTRAINT IDFC_ACSS_CRS_PK PRIMARY KEY (CD_INST, CD_IDFC_CRS)
);

CREATE TABLE IF NOT EXISTS DB2CBO.HST_IDFC_ACSS_CRS (
	CD_INST SMALLINT NOT NULL,
	CD_IDFC_CRS CHAR(8) NOT NULL,
	TS_ATL_HST TIMESTAMP NOT NULL,
	CD_EST_ATVD SMALLINT NOT NULL,
	CD_CRS INTEGER NOT NULL,
	NR_ULT_SEQL_IDFC INTEGER,
	CD_CHV_USU CHAR(8) NOT NULL,
	DT_ALT DATE NOT NULL,
	HR_ALT TIME NOT NULL,
	CD_OPRD_CRS INTEGER DEFAULT 0 NOT NULL,
	CD_ACSS_PRVR_OPRD INTEGER DEFAULT 0 NOT NULL,
	CD_LOJA_CRS INTEGER DEFAULT 0 NOT NULL,
	DT_INC_BLQ_NEGL DATE,
	DT_FIM_BLQ_NEGL DATE,
	CD_EST_ATVD_BLQ SMALLINT,
	CD_TIP_BLQ_NEGL SMALLINT,
	TX_JST_BLQ_NEGL VARCHAR(500),
	CONSTRAINT HST_IDFC_ACSS_CRS_PK PRIMARY KEY (CD_INST, CD_IDFC_CRS, TS_ATL_HST)
);

CREATE TABLE IF NOT EXISTS DB2CBO.GST_REDE_CRS_BCRO (
	CD_INST SMALLINT DEFAULT 1 NOT NULL,
	CD_GST_REDE_CRS INTEGER NOT NULL,
	CD_PERC_RCBT_TARF SMALLINT NOT NULL,
	CD_FMA_RCBT_TARF SMALLINT NOT NULL,
	CD_EST_ATVD SMALLINT NOT NULL,
	DT_CADM DATE NOT NULL,
	VL_LIM_ECXE_GST DECIMAL(17,2) NOT NULL,
	VL_ECXE_UTZD DECIMAL(17,2),
	IN_BLQ_AUTC CHAR(1),
	DD_RCBT_RMNC SMALLINT NOT NULL,
	DT_ULT_RCBT_RMNC DATE,
	IN_RCBT_RMNC_DT CHAR(1),
	CD_CHV_USU CHAR(8) NOT NULL,
	DT_ALT DATE NOT NULL,
	HR_ALT TIME NOT NULL,
	NM_GST_REDE CHAR(30),
	DT_CADM_GST_BC DATE DEFAULT '0001-01-01' NOT NULL,
	CD_CTR_PGTO INTEGER,
	IN_VLDC_IVT CHAR(1) DEFAULT 'N' NOT NULL,
	IN_RMNC_VLME_TRAN CHAR(1) DEFAULT 'N' NOT NULL,
	VL_LIM_CRS_PRPP DECIMAL(17,2) DEFAULT 0 NOT NULL,
	TX_NOTA_TCN_GST CHAR(100),
	PC_ECXE_GVTA_LOJA DECIMAL(4,2) DEFAULT 0 NOT NULL,
	CONSTRAINT GST_REDE_CRS_BCRO_PK PRIMARY KEY (CD_INST, CD_GST_REDE_CRS)
);


-- INÍCIO DA INCLUSÃO DE DADOS PARA TESTES DA CLASSE CorrespondenteBancarioService
-- CLASSE DE TESTES CorrespondenteBancarioServiceTest

INSERT INTO DB2CBO.CRS_BCRO
(CD_INST, CD_CRS, DT_CADM, CD_TIP_CRS, CD_EST_ATVD, VL_LIM_ECXE_CRS, VL_ECXE_UTZD, IN_BLQ_AUTC, CD_FMA_RCBT_RMNC,
CD_PERC_RCBT_RMNC, DD_RCBT_RMNC, DT_ULT_RCBT_RMNC, IN_RCBT_RMNC_DT, CD_RMS_ARQ_RTN, CD_FRNC_ETR_REDE,
CD_CHV_USU, DT_ALT, HR_ALT, CD_CVN_CRS, CD_GST_REDE_CRS, VL_PGTO_UTZD, VL_RCBT_UTZD, IN_AUTZ_AUTC, 
QT_DD_ALNM, NM_CRS, IN_ALNM_AUTC, IN_ANOT_CRD, IN_ANOT_CADL, TX_NOTA_TCN_CRS, QT_DD_ISN_ENCG)
VALUES(1, 123456789, CURRENT_DATE, 4, 3, 200, 300, '', 0, 0, 0, CURRENT_DATE, '', 0, 0, '',
CURRENT_DATE, CURRENT_TIMESTAMP, 0, 0, 0, 0, 'N', 2, 'TESTE', '', 'N', 'S', '', 0);

-- FIM DA INCLUSÃO DE DADOS PARA TESTES DA CLASSE CorrespondenteBancarioService


-- INÍCIO DA INCLUSÃO DE DADOS PARA TESTES DA CLASSE GestorRedeCorrespondenteBancarioService
-- CLASSE DE TESTES GestorRedeCorrespondenteBancarioServiceTest

INSERT INTO DB2CBO.CRS_BCRO
(CD_INST, CD_CRS, DT_CADM, CD_TIP_CRS, CD_EST_ATVD, VL_LIM_ECXE_CRS, VL_ECXE_UTZD, IN_BLQ_AUTC, CD_FMA_RCBT_RMNC,
CD_PERC_RCBT_RMNC, DD_RCBT_RMNC, DT_ULT_RCBT_RMNC, IN_RCBT_RMNC_DT, CD_RMS_ARQ_RTN, CD_FRNC_ETR_REDE,
CD_CHV_USU, DT_ALT, HR_ALT, CD_CVN_CRS, CD_GST_REDE_CRS, VL_PGTO_UTZD, VL_RCBT_UTZD, IN_AUTZ_AUTC, 
QT_DD_ALNM, NM_CRS, IN_ALNM_AUTC, IN_ANOT_CRD, IN_ANOT_CADL, TX_NOTA_TCN_CRS, QT_DD_ISN_ENCG)
VALUES(1, 123789456, CURRENT_DATE, 4, 3, 200, 300, '', 0, 0, 0, CURRENT_DATE, '', 0, 0, '',
CURRENT_DATE, CURRENT_TIMESTAMP, 0, 0, 0, 0, 'N', 2, 'TESTE', '', 'N', 'S', '', 0);

INSERT INTO DB2CBO.HST_CRS_BCRO
(CD_INST, CD_CRS, CD_GST_REDE_CRS, DT_ALT, HR_ALT, DT_CADM, CD_TIP_CRS, CD_EST_ATVD, VL_LIM_ECXE_CRS, VL_ECXE_UTZD, IN_BLQ_AUTC,
CD_FMA_RCBT_RMNC, CD_PERC_RCBT_RMNC, DD_RCBT_RMNC, DT_ULT_RCBT_RMNC, IN_RCBT_RMNC_DT, CD_RMS_ARQ_RTN,
CD_FRNC_ETR_REDE, CD_CHV_USU, CD_CVN_CRS, IN_AUTZ_AUTC, QT_DD_ALNM, CD_JST_ALT,
IN_ALNM_AUTC, IN_ANOT_CRD, IN_ANOT_CADL, TX_NOTA_TCN_CRS, QT_DD_ISN_ENCG)
VALUES(1, 123789456, 123789456, '1970-01-01' , '00:00:00', '1970-01-01', 4, 2, 1.00, 854578.99, '2', 1, 3, 10,
'1970-01-01', '0', 4, 1, 'F1146426', 4003, 'S', 2, 0, 'N', 'N', 'N', ' ', 0);

INSERT INTO DB2CBO.GST_REDE_CRS_BCRO
(CD_INST, CD_GST_REDE_CRS, CD_PERC_RCBT_TARF, CD_FMA_RCBT_TARF, CD_EST_ATVD, DT_CADM, VL_LIM_ECXE_GST,
VL_ECXE_UTZD, IN_BLQ_AUTC, DD_RCBT_RMNC, DT_ULT_RCBT_RMNC, IN_RCBT_RMNC_DT, CD_CHV_USU, DT_ALT, HR_ALT,
NM_GST_REDE, DT_CADM_GST_BC, CD_CTR_PGTO, IN_VLDC_IVT, IN_RMNC_VLME_TRAN, VL_LIM_CRS_PRPP, TX_NOTA_TCN_GST, PC_ECXE_GVTA_LOJA)
VALUES(1, 123789456, 0, 0, 0, '1970-01-01', 0, 0, '', 0, '1970-01-01', '', '', '1970-01-01', '00:00:00',
'', '2011-02-01', 0, 'N', 'N', 0, '', 0);

-- FIM DA INCLUSÃO DE DADOS PARA TESTES DA CLASSE GestorRedeCorrespondenteBancarioService


-- INÍCIO DA INCLUSÃO DE DADOS PARA TESTES DA CLASSE IdentificacaoAcessoCorrespondenteService
-- CLASSE DE TESTES IdentificacaoAcessoCorrespondenteServiceTest

INSERT INTO DB2CBO.CRS_BCRO
(CD_INST, CD_CRS, DT_CADM, CD_TIP_CRS, CD_EST_ATVD, VL_LIM_ECXE_CRS, VL_ECXE_UTZD, IN_BLQ_AUTC, CD_FMA_RCBT_RMNC,
CD_PERC_RCBT_RMNC, DD_RCBT_RMNC, DT_ULT_RCBT_RMNC, IN_RCBT_RMNC_DT, CD_RMS_ARQ_RTN, CD_FRNC_ETR_REDE,
CD_CHV_USU, DT_ALT, HR_ALT, CD_CVN_CRS, CD_GST_REDE_CRS, VL_PGTO_UTZD, VL_RCBT_UTZD, IN_AUTZ_AUTC, 
QT_DD_ALNM, NM_CRS, IN_ALNM_AUTC, IN_ANOT_CRD, IN_ANOT_CADL, TX_NOTA_TCN_CRS, QT_DD_ISN_ENCG)
VALUES(1, 159357852, CURRENT_DATE, 4, 3, 200, 300, '', 0, 0, 0, CURRENT_DATE, '', 0, 0, '',
CURRENT_DATE, CURRENT_TIMESTAMP, 0, 0, 0, 0, 'N', 2, 'TESTE', '', 'N', 'S', '', 0);

INSERT INTO DB2CBO.HST_CRS_BCRO
(CD_INST, CD_CRS, CD_GST_REDE_CRS, DT_ALT, HR_ALT, DT_CADM, CD_TIP_CRS, CD_EST_ATVD, VL_LIM_ECXE_CRS, VL_ECXE_UTZD, IN_BLQ_AUTC,
CD_FMA_RCBT_RMNC, CD_PERC_RCBT_RMNC, DD_RCBT_RMNC, DT_ULT_RCBT_RMNC, IN_RCBT_RMNC_DT, CD_RMS_ARQ_RTN,
CD_FRNC_ETR_REDE, CD_CHV_USU, CD_CVN_CRS, IN_AUTZ_AUTC, QT_DD_ALNM, CD_JST_ALT,
IN_ALNM_AUTC, IN_ANOT_CRD, IN_ANOT_CADL, TX_NOTA_TCN_CRS, QT_DD_ISN_ENCG)
VALUES(1, 159357852, 159357852, '1970-01-01' , '00:00:00', '1970-01-01', 4, 2, 1.00, 854578.99, '2', 1, 3, 10,
'1970-01-01', '0', 4, 1, 'F1146426', 4003, 'S', 2, 0, 'N', 'N', 'N', ' ', 0);

INSERT INTO DB2CBO.GST_REDE_CRS_BCRO
(CD_INST, CD_GST_REDE_CRS, CD_PERC_RCBT_TARF, CD_FMA_RCBT_TARF, CD_EST_ATVD, DT_CADM, VL_LIM_ECXE_GST,
VL_ECXE_UTZD, IN_BLQ_AUTC, DD_RCBT_RMNC, DT_ULT_RCBT_RMNC, IN_RCBT_RMNC_DT, CD_CHV_USU, DT_ALT, HR_ALT,
NM_GST_REDE, DT_CADM_GST_BC, CD_CTR_PGTO, IN_VLDC_IVT, IN_RMNC_VLME_TRAN, VL_LIM_CRS_PRPP, TX_NOTA_TCN_GST, PC_ECXE_GVTA_LOJA)
VALUES(1, 159357852, 0, 0, 0, '1970-01-01', 0, 0, '', 0, '1970-01-01', '', '', '1970-01-01', '00:00:00',
'', '2011-02-01', 0, 'N', 'N', 0, '', 0);

INSERT INTO DB2CBO.HST_IDFC_ACSS_CRS
(CD_INST, CD_IDFC_CRS, TS_ATL_HST, CD_CRS, CD_EST_ATVD, NR_ULT_SEQL_IDFC, CD_CHV_USU,
DT_ALT, HR_ALT, CD_OPRD_CRS, CD_ACSS_PRVR_OPRD, CD_LOJA_CRS,
DT_INC_BLQ_NEGL, DT_FIM_BLQ_NEGL, CD_EST_ATVD_BLQ, CD_TIP_BLQ_NEGL, TX_JST_BLQ_NEGL)
VALUES (1, 'J1234567', CURRENT_TIMESTAMP, 159357852, 2, 1, 'F1234567',
TRUNC(SYSDATE), CURRENT_TIMESTAMP, 1, 1, 1,
TRUNC(SYSDATE), TRUNC(SYSDATE), 2, 2, 'Texto do bloqueio');

INSERT INTO DB2CBO.IDFC_ACSS_CRS
(CD_INST, CD_IDFC_CRS, CD_CRS, CD_EST_ATVD, NR_ULT_SEQL_IDFC, CD_CHV_USU,
DT_ALT, HR_ALT, CD_OPRD_CRS, CD_ACSS_PRVR_OPRD, CD_LOJA_CRS,
DT_INC_BLQ_NEGL, DT_FIM_BLQ_NEGL, CD_EST_ATVD_BLQ, CD_TIP_BLQ_NEGL, TX_JST_BLQ_NEGL)
VALUES (1, 'J1234567', 159357852, 2, 1, 'F1234567',
TRUNC(SYSDATE), CURRENT_TIMESTAMP, 1, 1, 1,
TRUNC(SYSDATE), TRUNC(SYSDATE), 2, 2, 'Texto do bloqueio');

INSERT INTO DB2CBO.IDFC_ACSS_CRS
(CD_INST, CD_IDFC_CRS, CD_CRS, CD_EST_ATVD, NR_ULT_SEQL_IDFC, CD_CHV_USU,
DT_ALT, HR_ALT, CD_OPRD_CRS, CD_ACSS_PRVR_OPRD, CD_LOJA_CRS,
DT_INC_BLQ_NEGL, DT_FIM_BLQ_NEGL, CD_EST_ATVD_BLQ, CD_TIP_BLQ_NEGL, TX_JST_BLQ_NEGL)
VALUES (1, 'J1593578', 159357852, 2, 1, 'F1234567',
TRUNC(SYSDATE), CURRENT_TIMESTAMP, 1, 1, 1,
NULL, NULL, NULL, NULL, NULL);

INSERT INTO DB2CBO.IDFC_ACSS_CRS
(CD_INST, CD_IDFC_CRS, CD_CRS, CD_EST_ATVD, NR_ULT_SEQL_IDFC, CD_CHV_USU,
DT_ALT, HR_ALT, CD_OPRD_CRS, CD_ACSS_PRVR_OPRD, CD_LOJA_CRS,
DT_INC_BLQ_NEGL, DT_FIM_BLQ_NEGL, CD_EST_ATVD_BLQ, CD_TIP_BLQ_NEGL, TX_JST_BLQ_NEGL)
VALUES (1, 'J7894561', 159357852, 2, 1, 'F1234567',
TRUNC(SYSDATE), CURRENT_TIMESTAMP, 1, 1, 1,
TRUNC(SYSDATE), TRUNC(SYSDATE), 2, 2, 'Texto do bloqueio');

INSERT INTO DB2CBO.IDFC_ACSS_CRS
(CD_INST, CD_IDFC_CRS, CD_CRS, CD_EST_ATVD, NR_ULT_SEQL_IDFC, CD_CHV_USU,
DT_ALT, HR_ALT, CD_OPRD_CRS, CD_ACSS_PRVR_OPRD, CD_LOJA_CRS,
DT_INC_BLQ_NEGL, DT_FIM_BLQ_NEGL, CD_EST_ATVD_BLQ, CD_TIP_BLQ_NEGL, TX_JST_BLQ_NEGL)
VALUES (1, 'J4561239', 159357852, 2, 1, 'F1234567',
TRUNC(SYSDATE), CURRENT_TIMESTAMP, 1, 1, 1,
TRUNC(SYSDATE), TRUNC(SYSDATE), 2, 2, 'Texto do bloqueio');

INSERT INTO DB2CBO.IDFC_ACSS_CRS
(CD_INST, CD_IDFC_CRS, CD_CRS, CD_EST_ATVD, NR_ULT_SEQL_IDFC, CD_CHV_USU,
DT_ALT, HR_ALT, CD_OPRD_CRS, CD_ACSS_PRVR_OPRD, CD_LOJA_CRS,
DT_INC_BLQ_NEGL, DT_FIM_BLQ_NEGL, CD_EST_ATVD_BLQ, CD_TIP_BLQ_NEGL, TX_JST_BLQ_NEGL)
VALUES (1, 'J9865147', 9865147, 2, 1, 'F1234567',
TRUNC(SYSDATE), CURRENT_TIMESTAMP, 1, 1, 1,
NULL, NULL, NULL, NULL, NULL);

INSERT INTO DB2CBO.CRS_BCRO
(CD_INST, CD_CRS, DT_CADM, CD_TIP_CRS, CD_EST_ATVD, VL_LIM_ECXE_CRS, VL_ECXE_UTZD, IN_BLQ_AUTC, CD_FMA_RCBT_RMNC,
CD_PERC_RCBT_RMNC, DD_RCBT_RMNC, DT_ULT_RCBT_RMNC, IN_RCBT_RMNC_DT, CD_RMS_ARQ_RTN, CD_FRNC_ETR_REDE,
CD_CHV_USU, DT_ALT, HR_ALT, CD_CVN_CRS, CD_GST_REDE_CRS, VL_PGTO_UTZD, VL_RCBT_UTZD, IN_AUTZ_AUTC, 
QT_DD_ALNM, NM_CRS, IN_ALNM_AUTC, IN_ANOT_CRD, IN_ANOT_CADL, TX_NOTA_TCN_CRS, QT_DD_ISN_ENCG)
VALUES(1, 1593, CURRENT_DATE, 4, 3, 200, 300, '', 0, 0, 0, CURRENT_DATE, '', 0, 0, '',
CURRENT_DATE, CURRENT_TIMESTAMP, 0, 0, 0, 0, 'N', 2, 'TESTE', '', 'N', 'S', '', 0);

INSERT INTO DB2CBO.HST_CRS_BCRO
(CD_INST, CD_CRS, CD_GST_REDE_CRS, DT_ALT, HR_ALT, DT_CADM, CD_TIP_CRS, CD_EST_ATVD, VL_LIM_ECXE_CRS, VL_ECXE_UTZD, IN_BLQ_AUTC,
CD_FMA_RCBT_RMNC, CD_PERC_RCBT_RMNC, DD_RCBT_RMNC, DT_ULT_RCBT_RMNC, IN_RCBT_RMNC_DT, CD_RMS_ARQ_RTN,
CD_FRNC_ETR_REDE, CD_CHV_USU, CD_CVN_CRS, IN_AUTZ_AUTC, QT_DD_ALNM, CD_JST_ALT,
IN_ALNM_AUTC, IN_ANOT_CRD, IN_ANOT_CADL, TX_NOTA_TCN_CRS, QT_DD_ISN_ENCG)
VALUES(1, 1593, 123951, '1970-01-01' , '00:00:00', '1970-01-01', 4, 2, 1.00, 854578.99, '2', 1, 3, 10,
'1970-01-01', '0', 4, 1, 'F1146426', 4003, 'S', 2, 0, 'N', 'N', 'N', ' ', 0);

INSERT INTO DB2CBO.IDFC_ACSS_CRS
(CD_INST, CD_IDFC_CRS, CD_CRS, CD_EST_ATVD, NR_ULT_SEQL_IDFC, CD_CHV_USU,
DT_ALT, HR_ALT, CD_OPRD_CRS, CD_ACSS_PRVR_OPRD, CD_LOJA_CRS,
DT_INC_BLQ_NEGL, DT_FIM_BLQ_NEGL, CD_EST_ATVD_BLQ, CD_TIP_BLQ_NEGL, TX_JST_BLQ_NEGL)
VALUES (1, 'J1654821', 1593, 2, 1, 'F1234567',
TRUNC(SYSDATE), CURRENT_TIMESTAMP, 1, 1, 1,
TRUNC(SYSDATE), TRUNC(SYSDATE), 2, 2, 'Texto do bloqueio');

INSERT INTO DB2CBO.CRS_BCRO
(CD_INST, CD_CRS, DT_CADM, CD_TIP_CRS, CD_EST_ATVD, VL_LIM_ECXE_CRS, VL_ECXE_UTZD, IN_BLQ_AUTC, CD_FMA_RCBT_RMNC,
CD_PERC_RCBT_RMNC, DD_RCBT_RMNC, DT_ULT_RCBT_RMNC, IN_RCBT_RMNC_DT, CD_RMS_ARQ_RTN, CD_FRNC_ETR_REDE,
CD_CHV_USU, DT_ALT, HR_ALT, CD_CVN_CRS, CD_GST_REDE_CRS, VL_PGTO_UTZD, VL_RCBT_UTZD, IN_AUTZ_AUTC, 
QT_DD_ALNM, NM_CRS, IN_ALNM_AUTC, IN_ANOT_CRD, IN_ANOT_CADL, TX_NOTA_TCN_CRS, QT_DD_ISN_ENCG)
VALUES(1, 1594, CURRENT_DATE, 4, 3, 200, 300, '', 0, 0, 0, CURRENT_DATE, '', 0, 0, '',
CURRENT_DATE, CURRENT_TIMESTAMP, 0, 0, 0, 0, 'N', 2, 'TESTE', '', 'N', 'S', '', 0);

INSERT INTO DB2CBO.IDFC_ACSS_CRS
(CD_INST, CD_IDFC_CRS, CD_CRS, CD_EST_ATVD, NR_ULT_SEQL_IDFC, CD_CHV_USU,
DT_ALT, HR_ALT, CD_OPRD_CRS, CD_ACSS_PRVR_OPRD, CD_LOJA_CRS,
DT_INC_BLQ_NEGL, DT_FIM_BLQ_NEGL, CD_EST_ATVD_BLQ, CD_TIP_BLQ_NEGL, TX_JST_BLQ_NEGL)
VALUES (1, 'J1654829', 1594, 2, 1, 'F1234567',
TRUNC(SYSDATE), CURRENT_TIMESTAMP, 1, 1, 1,
TRUNC(SYSDATE), TRUNC(SYSDATE), 2, 2, 'Texto do bloqueio');

INSERT INTO DB2CBO.IDFC_ACSS_CRS
(CD_INST, CD_IDFC_CRS, CD_CRS, CD_EST_ATVD, NR_ULT_SEQL_IDFC, CD_CHV_USU,
DT_ALT, HR_ALT, CD_OPRD_CRS, CD_ACSS_PRVR_OPRD, CD_LOJA_CRS,
DT_INC_BLQ_NEGL, DT_FIM_BLQ_NEGL, CD_EST_ATVD_BLQ, CD_TIP_BLQ_NEGL, TX_JST_BLQ_NEGL)
VALUES (1, 'J1654711', 1595, 2, 1, 'F1234567',
TRUNC(SYSDATE), CURRENT_TIMESTAMP, 1, 1, 1,
TRUNC(SYSDATE), TRUNC(SYSDATE), 2, 2, 'Texto do bloqueio');

INSERT INTO DB2CBO.IDFC_ACSS_CRS
(CD_INST, CD_IDFC_CRS, CD_CRS, CD_EST_ATVD, NR_ULT_SEQL_IDFC, CD_CHV_USU,
DT_ALT, HR_ALT, CD_OPRD_CRS, CD_ACSS_PRVR_OPRD, CD_LOJA_CRS,
DT_INC_BLQ_NEGL, DT_FIM_BLQ_NEGL, CD_EST_ATVD_BLQ, CD_TIP_BLQ_NEGL, TX_JST_BLQ_NEGL)
VALUES (1, 'J1234568', 159357852, 2, 1, 'F1234567',
TRUNC(SYSDATE), CURRENT_TIMESTAMP, 1, 1, 1,
TRUNC(SYSDATE), TRUNC(SYSDATE), 2, 2, 'Texto do bloqueio');

-- FIM DA INCLUSÃO DE DADOS PARA TESTES DA CLASSE IdentificacaoAcessoCorrespondenteService


-- INÍCIO DA INCLUSÃO DE DADOS PARA TESTES DA CLASSE Op6463945v1
-- CLASSE DE TESTES Op6463945v1Test

INSERT INTO DB2CBO.IDFC_ACSS_CRS
(CD_INST, CD_IDFC_CRS, CD_CRS, CD_EST_ATVD, NR_ULT_SEQL_IDFC, CD_CHV_USU,
DT_ALT, HR_ALT, CD_OPRD_CRS, CD_ACSS_PRVR_OPRD, CD_LOJA_CRS,
DT_INC_BLQ_NEGL, DT_FIM_BLQ_NEGL, CD_EST_ATVD_BLQ, CD_TIP_BLQ_NEGL, TX_JST_BLQ_NEGL)
VALUES (1, 'J1593111', 159357852, 2, 1, 'F1234567',
TRUNC(SYSDATE), CURRENT_TIMESTAMP, 1, 1, 1,
NULL, NULL, NULL, NULL, NULL);

-- FIM DA INCLUSÃO DE DADOS PARA TESTES DA CLASSE Op6463945v1


-- INÍCIO DA INCLUSÃO DE DADOS PARA TESTES DA CLASSE Op6463960v1
-- CLASSE DE TESTES Op6463960v1Test

INSERT INTO DB2CBO.IDFC_ACSS_CRS
(CD_INST, CD_IDFC_CRS, CD_CRS, CD_EST_ATVD, NR_ULT_SEQL_IDFC, CD_CHV_USU,
DT_ALT, HR_ALT, CD_OPRD_CRS, CD_ACSS_PRVR_OPRD, CD_LOJA_CRS,
DT_INC_BLQ_NEGL, DT_FIM_BLQ_NEGL, CD_EST_ATVD_BLQ, CD_TIP_BLQ_NEGL, TX_JST_BLQ_NEGL)
VALUES (1, 'J7894516', 159357852, 2, 1, 'F1234567',
TRUNC(SYSDATE), CURRENT_TIMESTAMP, 1, 1, 1,
TRUNC(SYSDATE), TRUNC(SYSDATE), 2, 2, 'Texto do bloqueio');

-- FIM DA INCLUSÃO DE DADOS PARA TESTES DA CLASSE Op6463960v1


-- INÍCIO DA INCLUSÃO DE DADOS PARA TESTES DA CLASSE Op6463996v1
-- CLASSE DE TESTES Op6463996v1Test

INSERT INTO DB2CBO.IDFC_ACSS_CRS
(CD_INST, CD_IDFC_CRS, CD_CRS, CD_EST_ATVD, NR_ULT_SEQL_IDFC, CD_CHV_USU,
DT_ALT, HR_ALT, CD_OPRD_CRS, CD_ACSS_PRVR_OPRD, CD_LOJA_CRS,
DT_INC_BLQ_NEGL, DT_FIM_BLQ_NEGL, CD_EST_ATVD_BLQ, CD_TIP_BLQ_NEGL, TX_JST_BLQ_NEGL)
VALUES (1, 'J4561293', 159357852, 2, 1, 'F1234567',
TRUNC(SYSDATE), CURRENT_TIMESTAMP, 1, 1, 1,
TRUNC(SYSDATE), TRUNC(SYSDATE), 2, 2, 'Texto do bloqueio');

-- FIM DA INCLUSÃO DE DADOS PARA TESTES DA CLASSE Op6463996v1


CREATE SCHEMA IF NOT EXISTS exemplo AUTHORIZATION sa;
